---
image: "gitlab-registry.cern.ch/linuxsupport/alma9-base"

stages:
- "lint"
- "validate"
- "build"
- "tagging"

lint_general:
  stage: "lint"
  image: "golang:1.24"
  allow_failure: true
  script:
  - "go install
    github.com/editorconfig-checker/editorconfig-checker/v3/cmd/editorconfig-checker@latest"
  - "editorconfig-checker ."

lint_go_style:
  stage: "lint"
  image: "golangci/golangci-lint:latest"
  allow_failure: true
  artifacts:
    reports:
      codequality:
      - "gl-code-quality-report.json"
  script:
  - "golangci-lint run --config=.golangci.yaml
    --output.code-climate.path=gl-code-quality-report.json"

lint_markdown_style:
  stage: "lint"
  image: "node:20"
  allow_failure: true
  script:
  - "npm install -g markdownlint-cli"
  - "markdownlint \"**/*.md\""

lint_markdown_spell:
  stage: "lint"
  image: "node:20"
  allow_failure: true
  script:
  - "npm install -g cspell"
  - "cspell \"**/*.md\""

lint_yaml_style:
  stage: "lint"
  allow_failure: true
  script:
  - "dnf install -y epel-release"
  - "dnf install -y yamllint"
  - "yamllint ."

test:
  stage: "validate"
  image: "golang:1.24"
  script:
  - "go test -v ./..."

build_image:
  stage: build
  variables:
    TO: "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
  trigger:
    include:
      - project: 'ci-tools/docker-builder'
        file: '/ci.yml'
    strategy: depend

tag_docker_image_in_default_branch:
  stage: tagging
  image: gitlab-registry.cern.ch/ci-tools/docker-builder/tools
  variables:
    GIT_STRATEGY: none
  dependencies: []
  script:
    - source /kaniko/auth.sh
    - crane tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}" "${CI_COMMIT_SHORT_SHA}-rc"
    - crane validate --remote "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}-rc"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

tag_docker_image_with_git_tag:
  stage: tagging
  image: gitlab-registry.cern.ch/ci-tools/docker-builder/tools
  variables:
    GIT_STRATEGY: none
  dependencies: []
  script:
    - source /kaniko/auth.sh
    - crane tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}" "${CI_COMMIT_TAG}"
    - crane validate --remote "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
  rules:
    - if: $CI_COMMIT_TAG
