image: golang:1.24

stages:
  - lint
  - validate

lint:
  stage: lint
  image: golangci/golangci-lint:latest
  allow_failure: true
  script:
    - golangci-lint run --config=.golangci.yaml

test:
  stage: validate
  script:
    - go test -v ./...
