---
extends: "default"
rules:
  empty-lines:
    max: 1
  indentation:
    indent-sequences: false
    spaces: 2
  key-ordering:
    ignore:
    - ".gitlab-ci.yml"
    ignored-keys: []
  line-length:
    allow-non-breakable-words: true
    max: 80
  new-line-at-end-of-file: {}
  new-lines:
    type: "unix"
  quoted-strings:
    allow-quoted-quotes: false
    check-keys: false
    quote-type: "double"
    required: true
  trailing-spaces: {}
